// Paths of the HTTP API. The front end and the route handlers take them from here, nowhere else.
export const API_ROUTES = {
  calls: '/api/calls',
  backfillCalls: '/api/calls/backfill',
  violations: '/api/violations',
  violationStats: '/api/violations/stats',
  unblockExpiredPenalties: '/api/violations/unblock_expired_penalties_users',
  restorePenalties: '/api/penalties/restore',
  gateUsers: '/api/users',
  addGateUser: '/api/users/add_user',
  editGateUser: '/api/users/edit_user',
  deleteGateUser: '/api/users/delete_user',
  exportGateUsers: '/api/users/export',
  importGateUsers: '/api/users/import',
  syncGateUsersFromDirectory: '/api/users/sync_from_directory',
  access: '/api/access',
  accessActors: '/api/access/actors',
  pageViews: '/api/access/page-views',
  activity: '/api/activity',
  activityActors: '/api/activity/actors',
  register: '/api/register',
  deleteFiles: '/api/cloudinary/delete_files',
} as const;
